### ISSUE TITLE
[BUG] Longitude and Latitude are swapped

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/raster-loader#73]
**Bug Description**

I tried importing this file into BQ:

```bash
wget http://www.cec.org/files/atlas_layers/0_reference/0_03_elevation/elevation_tif.zip
unzip elevation_tif.zip
carto bigquery upload \
    --file_path Elevation_TIF/NA_Elevation/data/na_elevation.tif \
    --project cartodb-data-engineering-team \
    --dataset jgoizueta_tmp \
    --table dem \
    --overwrite
```

But the resulting table seems to have the longitude and latitude in the reverse order in the columns for the block corner coordinates:

```sql
SELECT
  MAX(greatest(lat_nw, lat_ne, lat_sw, lat_se)) AS lat_max,
  MIN(least(lat_nw, lat_ne, lat_sw, lat_se)) AS lat_min,
  MAX(greatest(lon_nw, lon_ne, lon_sw, lon_se)) AS lon_max,
  MIN(least(lon_nw, lon_ne, lon_sw, lon_se)) AS lon_min
FROM `cartodb-data-engineering-team.jgoizueta_tmp.dem`
```

Result:

```json
[{
  "lat_max": "179.98874485301658",
  "lat_min": "-179.99930842865948",
  "lon_max": "89.699076924372292",
  "lon_min": "-4.5982238825563462"
}]
```

**System information**

```text
Raster Loader version: 0.1.1.dev3+gfc88b40.d20230118
Python version: 3.9.16
Platform: macOS-13.1-x86_64-i386-64bit
System version: Darwin 22.2.0
Machine: x86_64
Processor: i386
Architecture: 64bit
```

**Comment by jgoizueta** [comment]
Same thing happens with this file:

https://github.com/CartoDB/raster-loader/blob/61ccde5dee6d2b01b102960e1a2b3753ab415e9e/raster_loader/tests/fixtures/world_zoom_0-2.cog.tif?raw=true

probably related to #46

**Comment by francois-baptiste** [comment]
Thanks for the report @jgoizueta
I also found that the Longitude and Latitude were swapped in this commit https://github.com/CartoDB/raster-loader/pull/72/commits/9e76b56ae8e99d6dad1bbca7e8bc3abb52e4c690 but I thought it was only for quadbin.

Let me do a PR to fix that!
