### ISSUE TITLE
Upload every level of of a pyramidal cloud optimised geotiff and upload

### ISSUE THREAD

**Issue by francois-baptiste** [CartoDB/raster-loader#84]
Upload every level of of a pyramidal cloud optimised geotiff and upload and add a new column to reference the aggregation level

**Comment by jatorre** [comment]
So, is this actually possible right now?? Can we store the entire pyramid?

**Comment by jatorre** [comment]
@Jesus89

**Comment by Jesus89** [comment]
This was not included in the GA initiative, so the ticket was closed. We can re-open if this is implemented in the future.

cc @ernesmb

**Comment by jatorre** [comment]
Yes keep it open as this will be really useful for visualization.

Looks like we had it implemented but the APIs on the backend side did not
implement it

**Comment by Jesus89** [comment]
ok :+1:

**Comment by Jesus89** [comment]
Done here https://github.com/CartoDB/raster-loader/pull/140
